### ISSUE TITLE
No need of using Library for Material dialog.

### ISSUE THREAD

**Issue by TakeoffAndroid** [Angtrim/Android-Five-Stars-Library#1]
Hello,

I really appreciate your commitment and dedication towards this wonderful repo. It is glad that you have released this completely as open source. But I have a concern regarding the usage of material dialogs library https://github.com/afollestad/material-dialogs. Instead of using this library you could achieve this with by implementing AppCompatAlertDialog. You have all the features to customize according to your need. Please try to change, so that your project will not be dependent on other libraries. For further regarding this visit my blog http://takeoffandroid.com/dialog/material-alertdialog-using-appcompat-v22-1-0/

Thanks,
TakeOff Android

**Comment by Angtrim** [comment]
I will change the project soon.
Closed
